"""Add ExerciseEquipment enum

Revision ID: 2d320ef25699
Revises: 31012346ee97
Create Date: 2026-08-03 15:21:22.703362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d320ef25699'
down_revision: Union[str, Sequence[str], None] = '31012346ee97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'equipment')
    
    exercise_equipment_enum = sa.Enum('BARBELL', 'DUMBBELL', 'KETTLEBELL', 'CABLE', 'MACHINE', 'SMITH_MACHINE', 'BODYWEIGHT', 'RESISTANCE_BAND', 'OTHER', name='exerciseequipment')
    exercise_equipment_enum.create(op.get_bind())
    
    op.add_column('exercises', sa.Column('equipment', exercise_equipment_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'equipment')
    
    exercise_equipment_enum = sa.Enum('BARBELL', 'DUMBBELL', 'KETTLEBELL', 'CABLE', 'MACHINE', 'SMITH_MACHINE', 'BODYWEIGHT', 'RESISTANCE_BAND', 'OTHER', name='exerciseequipment')
    exercise_equipment_enum.drop(op.get_bind())
    
    op.add_column('exercises', sa.Column('equipment', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
