"""Add Clerk ID and Import Traceability

Revision ID: 31012346ee97
Revises: 6def4cec0a27
Create Date: 2026-08-01 23:52:59.016718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31012346ee97'
down_revision: Union[str, Sequence[str], None] = '6def4cec0a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('import_jobs', sa.Column('source_url', sa.String(), nullable=False))
    op.create_index(op.f('ix_import_jobs_source_url'), 'import_jobs', ['source_url'], unique=False)
    op.create_foreign_key(None, 'import_jobs', 'users', ['user_id'], ['id'])
    op.add_column('import_logs', sa.Column('job_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'import_logs', 'import_jobs', ['job_id'], ['id'])
    op.add_column('users', sa.Column('clerk_id', sa.String(), nullable=False))
    op.create_index(op.f('ix_users_clerk_id'), 'users', ['clerk_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_clerk_id'), table_name='users')
    op.drop_column('users', 'clerk_id')
    op.drop_constraint(None, 'import_logs', type_='foreignkey')
    op.drop_column('import_logs', 'job_id')
    op.drop_constraint(None, 'import_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_import_jobs_source_url'), table_name='import_jobs')
    op.drop_column('import_jobs', 'source_url')
    op.drop_column('import_jobs', 'user_id')
    # ### end Alembic commands ###
